### PR TITLE
Fix broken link in AWS document

### PR DESCRIPTION
**Pull request by ashley314**
## Description

Fixing a broken link found in the documentation. 

## Definition of Done

Link works and points to correct location. 

## Dependencies

None

## Impact

None

### CODE REVIEW

**Review by climbfuji — CHANGES_REQUESTED** [review]
Thanks for this fix. I noticed that the readthedocs build is failing: https://readthedocs.com/projects/jointcenterforsatellitedataassimilation-jedi-docs/builds/1461786/

It's got to do with a recent update to urllib. I fixed that in spack-stack by adding
```
urllib3<2
```
to `requirements.txt`. This file is in the top-level directory of jedi-docs. Can you make this change please and push to your branch?

**Comment by ashley314** [comment]
@climbfuji Added!

**Review by climbfuji — APPROVED** [review]
readthedocs build is working again!

**Review by eap — APPROVED** [review]

**Comment by fabiolrdiniz** [comment]
Too late... thanks, @ashley314!

**Pull request merged**
