### PR TITLE
Update localensembleda.rst

### PR DESCRIPTION
**Pull request by frolovsa**
## Description
Update documentation to be consistent with 
https://github.com/JCSDA-internal/oops/pull/1776

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
Thank you for updating the documentation @frolovsa 👍

**Review by cmgas — APPROVED** [review]

**Comment by climbfuji** [comment]
@shlyaeva @frolovsa I just saw this PR. I can merge it into the internal repo (this PR is for public), which will then update the public code automatically. But there is a conflict that needs to be resolved:
```
 observations:
<<<<<<< bufix/halo_distribution
 - obs space:
     distribution:
        name: Halo
        halo size: 5000e3
=======
   observers:
   - obs space:
       distribution: Halo 
>>>>>>> develop
```

**Comment by shlyaeva** [comment]
@climbfuji thank you! I haven't realized it was open in public repo. I've just resolved the conflict.

**Comment by climbfuji** [comment]
Ok, I can't merge it there, so I will duplicate the PR for JCSDA-internal and ask you to check it

**Comment by climbfuji** [comment]
Replaced by https://github.com/JCSDA-internal/jedi-docs/pull/538 for JCSDA-internal.

**Pull request closed without merging**
